import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="place-items-center">
          <header>
            <NavBar />
          </header>
          <main className="width-2/3">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
